/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladores;

/**
 *
 * @author ASUS
 */
public enum Tokens {
    coment_1,coment_2,include,h,
    id1,id2,id3,id4,id5,id6,id7,id8,id9,id10,id11,id12,id13,id14,id15,id16,id17,id18,
    id19,id20,id21,id22,id23,id24,id25,id26,GETCGETS,ISPUNC,PUTC,
    ELLIPSIS,COLONCOLON,DOTSTAR,ADDEQ,SUBEQ,MULEQ,DIVEQ,MODEQ,XOREQ,ANDEQ,OREQ,SL,SR,
    SLEQ,EQ,NOTEQ,LTEQ,GTEQ,ANDAND,OROR,PLUSPLUS,MINUSMINUS,ARROWSTAR,
    ARROW,ASM,AUTO,BOOL,BREAK,CASE,CATCH,CHAR,CLASS,CONST,CONST_CAST,CONTINUE,
    DEFAULT,DELETE,DO,DOUBLE,DYNAMIC_CAST,ELSE,ENUM,EXPLICIT,EXPORT,EXTERN,FALSE,SREQ,
    FLOAT,FOR,FRIEND,GOTO,IF,INLINE,INT,LONG,MUTABLE,NAMESPACE,NEW,OPERATOR,PRIVATE,
    PROTECTED,PUBLIC,REGISTER,REINTERPRET_CAST,RETURN,SHORT,SIGNED,SIZEOF,STATIC,
    STATIC_CAST,STRUCT,SWITCH,TEMPLATE,THIS,THROW,TRUE,TRY,TYPEDEF,TYPEID,TYPENAME,
    UNION,UNSIGNED,USING,VIRTUAL,VOID,VOLATILE,WCHAR_T,WHILE,ident,numero,Main,Linea,ERROR, BEGIN, END,
    CBEGIN, CEND, REND, RBEGIN, CRBEGIN, CREND, COUT, CIN, ISDIGIT,ISCNTRL,ISALPHA,ISALNUM,ISGRAPH,ISLOWER, 
    ISPRINT, ISPUNCT,ISSPACE,ISUPPER,ISXDIGIT,FPRINTF,FSCANF,PRINTF,SCANF,SNPRINTF,SPRINTF,SSCANF,VFPRINTF,
    VFSCANF,VPRINTF,VSCANF,VSNPRINTF, VSPRINTF,VSSCANF, REMOVE,RENAME,TMPFILE,TMPNAM,FCLOSE,
    FFLUSH,FOPEN,FREOPEN,SETBUF,SETVBUF, TOLOWER, TOUPPER, FECLEAREXCEPT, FERAISEEXCEPT, FEGETEXCEPTFLAG,
    FESETEXCEPTFLAG, FEGETROUND, FESETROUND, FEGETENV, FESETENV,FEHOLDEXCEPT, FEUPDATEENV, FETESTEXCEPT,
    SETLOCALE,LOCALECONV, COS,SIN,TAN, ACOS, ASIN, ATAN, ATAN2, COSH, SINH, TANH, ACOSH, ASINH, ATANH,
    EXP,FREXP, LDEXP, LOG, LOG10, MODF, EXP2, EXPM1, ILOGB, LOG1P, LOG2, SCALBN, SCALBLN,POW,SQRT,CBRT,HYPOT,
    ERF,ERFC,TGAMMA,LGAMMA,CEIL,FLOOR, FMOD, TRUNC, ROUND, LROUND, LLROUND, RINT, LRINT, LLRINT, NEARBYINT,
    REMAINDER,REMQUO,COPYSIGN,NAN,NEXTAFTER, NEXTTOWARD, FDIM, FMAX, FMIN, FABS, ABS, FMA, LONGJMP, SIGNAL, RAISE,
    FGETC,FGETS,FPUTC,FPUTS,GETC,GETCHAR,GETS,PUTCHAR,PUTS,UNGETC,FREAD,FWRITE,FGETPOS,FSEEK,FSETPOS,
    FTELL,REWIND,CLEARERR,FEOF,FERROR,PERROR,ATOF,ATOI,ATOL,ATOLL,STRTOD,STRTOF,STRTOL,STRTOLD,STRTOLL,STRTOUL,
    STRTOULL,RAND,SRAND,CALLOC,FREE,MALLOC,REALLOC,ABORT,ATEXIT,AT_QUICK_EXIT,EXIT,GETENV,QUICK_EXIT,SYSTEM,_EXIT,
    BSEARCH,QSORT,DIV,LABS,LDIV,LLABS,LLDIV,MBLEN,MBTOWC,WCTOMB,MBSTOWCS,WCSTOMBS,MEMCPY,MEMMOVE,STRCPY,STRNCPY,
    STRCAT,STRNCAT,MEMCMP,STRCMP,STRXFRM,MEMCHR,STRCHR,STRCSPN,STRPBRK,STRRCHR,STRSPN,STRSTR,STRTOK,MEMSET,STRERROR,
    STRLEN,CLOCK,DIFFTIME,MKTIME,TIME,ASCTIME,CTIME,GMTIME,LOCALTIME,STRFTIME,FGETWC,FGETWS,FPUTWC,FPUTWS,FWIDE,FWPRINTF,
    FWSCANF,GETWC,GETWCHAR,PUTWC,PUTWCHAR,SWPRINTF,SWSCANF,UNGETWC,VFWPRINTF,VFWSCANF,VWPRINTF,VWSCANF,WPRINTF,WSCANF,
    WCSTOD,WCSTOF,WCSTOL,WCSTOLD,WCSTOLL,WCSTOUL,WCSTOULL,BTOWC,MBRLEN,MBRTOWC,MBSINIT,MBSRTOWCS,WCRTOMB,WCTOB,WCSRTOMBS,
    WCSCAT,WCSCHR,WCSCMP,WCSCOLL,WCSCPY,WCSCSPN,WCSLEN,WCSNCAT,WCSNCMP,WCSNCPY,WCSPBRK,WCSRCHR,WCSSPN,WCSSTR,WCSTOK,
    WCSXFRM,WMEMCHR,WMEMCMP,WMEMCPY,WMEMMOVE,WMEMSET,WCSFTIME,ISWALNUM,ISWALPHA,ISWBLANK,ISWCNTRL,ISWDIGIT,ISWGRAPH,
    ISWLOWER,ISWPRINT,ISWPUNCT,ISWSPACE,ISWUPPER,ISWXDIGIT,TOWLOWER,TOWUPPER,ISWCTYPE,TOWCTRANS,WCTRANS,WCTYPE,CERR,CLOG,
    WCIN,WCOUT,WCERR,WCLOG,ISTREAM,IOSTREAM,WISTREAM,WIOSTREAM,OSTREAM,WOSTREAM,ENDS,ENDL,FLUSH
}
